version: '3.8'

services:
  core-api:
    build:
      context: ./services/core-api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=disco_core
      - DB_USER=disco_user
      - DB_PASSWORD=disco_password
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
      - redis

  location-service:
    build:
      context: ./services/location-service
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=disco_users
      - DB_USER=disco_user
      - DB_PASSWORD=disco_password
    depends_on:
      - postgres

  matching-service:
    build:
      context: ./services/matching-service
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  postgres:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=disco_user
      - POSTGRES_PASSWORD=disco_password
      - POSTGRES_DB=disco_core
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
